// Octagon Security — Service page content data
// All copy is sourced verbatim or closely paraphrased from octagonsecured.com
// Pages marked "STUB" need content filled in from the live site next pass.

window.OS_SERVICES_DATA = {

  'home-security': {
    slug: 'home-security',
    title: 'Home & Business Security System Installation',
    location: 'Miami, Florida',
    hero_subtitle: 'Experience Peace of Mind with Reliable Alarm Protection',
    intro: 'At Octagon Security, we provide professional security system installation for businesses and homeowners across Miami-Dade, Broward, and Palm Beach. Our systems are designed for reliability, ease of use, and long-term performance — whether you need a simple alarm system or a fully integrated solution. We focus on fast response, clean installations, and ongoing support, which is why most of our work comes from repeat clients and referrals.',
    intro2: 'With years of hands-on experience, we design and install security systems that are built for real-world use — whether it\'s a residential property or a large commercial facility. We focus on proper system design, clean installation, and long-term reliability so your system performs the way it should from day one. Beyond installation, we provide ongoing support, system upgrades, and monitoring services to keep everything running smoothly.',
    icon: 'shield-check',
    image: '../../assets/svc-home-business.png',
    features: [
      {
        title: 'Complete Security System Solutions',
        bullets: ['CCTV and video surveillance', 'Burglar alarm systems with 24/7 monitoring', 'Fire alarm systems and inspections', 'Access control and keyless entry', 'Structured cabling infrastructure'],
        note: 'Every system is tailored to your property, ensuring proper coverage, clean integration, and reliable long-term performance.'
      },
      {
        title: 'Built for Homes & Commercial Properties',
        bullets: ['Residential homes and multi-family properties', 'Warehouses and industrial facilities', 'Offices and commercial buildings', 'Retail and mixed-use spaces'],
        note: 'Whether it\'s a new installation or an upgrade, we provide systems that are scalable, easy to manage, and built to last.'
      },
      {
        title: 'Fast Response & Professional Installation',
        bullets: ['Fast response to new inquiries', 'Quick turnaround on quotes and scheduling', 'Efficient, clean installations'],
        note: 'Our clients rely on us to respond when it matters — and follow through.'
      },
      {
        title: 'Integrated Systems That Work Together',
        bullets: ['Centralized monitoring', 'Remote access', 'Real-time alerts'],
        note: 'Your cameras, alarms, access control, and fire systems can be integrated into one platform.'
      },
      {
        title: 'Ongoing Service & Support',
        bullets: ['System maintenance and inspections', 'Troubleshooting and repairs', 'Monitoring services', 'System upgrades as your needs grow'],
        note: 'Most of our clients continue working with us because we stay responsive and involved long after installation.'
      },
      {
        title: 'Serving South Florida',
        bullets: ['Miami', 'Doral', 'Fort Lauderdale', 'Hollywood', 'Boca Raton', 'Surrounding areas'],
        note: ''
      },
    ],
    benefits: [
      { title: 'Enhanced Property Protection', body: 'Detects unauthorized entry instantly, helping prevent theft, damage, and unauthorized access. High-quality equipment and precise installation ensure that entry points are monitored and risks are minimized.' },
      { title: 'Remote Access & Alerts', body: 'Stay connected to your system with real-time notifications and control from your phone or device. Early detection of suspicious activity enhances personal safety and provides time to take action.' },
      { title: '24/7 Monitoring & Response', body: 'Modern security systems allow constant monitoring through mobile apps, computer dashboards, or control panels. Professional monitoring ensures alarms are handled quickly and the proper response is triggered.' },
      { title: 'Visible Deterrence', body: 'Visible security cameras, alarm systems, and access controls act as strong deterrents against potential intruders. Professionally installed systems reduce the likelihood of break-ins and unauthorized entry.' },
      { title: 'System Integration', body: 'Works seamlessly with cameras, access control, and other systems for complete protection. Integration enhances convenience and safety by enabling control of multiple systems from one centralized platform.' },
      { title: 'Scalable & Reliable', body: 'Easily expand your system as needed with dependable performance over time. The long-term financial benefits of security investment outweigh initial costs by safeguarding assets.' },
    ],
    closing_title: 'Safeguarding Properties with Expert Security Installation',
    closing: 'Choosing professional security system installation ensures your property is properly protected, your system is installed correctly, and everything works together as intended. At Octagon Security, we provide reliable solutions for homes and businesses across South Florida, backed by fast response and ongoing support.',
    faqs: [
      { q: 'How long does it take to install a home or business security system?', a: 'Installation typically takes between 4 to 8 hours, depending on system complexity and property size. Our team works efficiently to minimize disruption, ensuring devices, cameras, and alarms are calibrated properly and fully operational.' },
      { q: 'Can security systems be upgraded over time?', a: 'Absolutely. Security systems are designed with scalability in mind. Additional cameras, sensors, or access control components can be integrated seamlessly as your needs grow.' },
      { q: 'What types of properties can your security systems protect?', a: 'Our systems are suitable for single-family homes, multi-unit residences, small offices, large commercial complexes, and retail spaces. Each installation is customized based on property layout and security needs.' },
      { q: 'How does professional installation improve system effectiveness?', a: 'Professional installation ensures optimal placement of cameras, alarms, and sensors, reducing blind spots and minimizing false alarms. Expert calibration guarantees reliability and system integration.' },
      { q: 'Does Octagon Security serve all areas in South Florida?', a: 'Yes, Octagon Security provides services across Miami-Dade, Broward, Palm Beach, and Monroe Counties. Our local expertise ensures each installation accounts for regional security needs and building structures.' },
    ],
  },

  'cameras': {
    slug: 'cameras',
    title: 'Security Camera Installation & Video Surveillance Systems in South Florida',
    location: 'South Florida',
    hero_subtitle: 'Professional Surveillance Systems You Can Rely On',
    intro: 'At Octagon Security, we provide professional security camera installation and video surveillance systems for businesses and homes across Miami-Dade, Broward, and Palm Beach. Our systems are designed for clear visibility, remote access, and long-term reliability — whether you need basic coverage or a fully integrated commercial system.',
    intro2: 'Modern security cameras do more than just record — they give you full control over your property. Our systems include high-definition and 4K camera options, night vision and low-light performance, motion detection and real-time alerts, remote access from mobile devices, and cloud and local recording options.',
    icon: 'camera',
    image: '../../assets/svc-cameras.png',
    features: [
      { title: 'Designed for Homes & Commercial Properties', bullets: ['Residential homes and multi-family properties', 'Warehouses and distribution centers', 'Office buildings and commercial spaces', 'Retail and mixed-use properties'], note: 'Each system is designed to eliminate blind spots and provide reliable coverage where it matters most.' },
      { title: 'Commercial Camera Systems for Larger Facilities', bullets: ['Large open areas and high ceilings', 'Loading docks and exterior coverage', 'Perimeter monitoring and entry points', 'License plate and access point visibility'], note: 'Advanced systems can include multi-sensor or panoramic cameras that reduce blind spots across large areas.' },
      { title: 'Clean Installation & Proper Infrastructure', bullets: ['Clean, organized cabling', 'Proper camera placement and angles', 'Secure mounting and weather protection', 'Integration with existing systems'], note: 'Our structured cabling experience ensures your system is reliable from day one.' },
      { title: 'Remote Access & Monitoring', bullets: ['View live footage from your phone or computer', 'Receive alerts for motion or activity', 'Access recorded footage instantly', 'Optional monitoring integration'], note: 'Modern systems allow full control and visibility no matter where you are.' },
      { title: 'Upgrades & System Expansions', bullets: ['Upgrade outdated cameras', 'Improve image quality and coverage', 'Add additional cameras or storage', 'Integrate with alarms or access control'], note: 'We help bring older systems up to current standards without starting from scratch.' },
      { title: 'Fast Response & Ongoing Support', bullets: ['Quick response to new inquiries', 'Fast scheduling and installation', 'Ongoing service and troubleshooting'], note: 'With over 65 years of combined experience, we provide support our clients rely on long-term.' },
    ],
    benefits: [
      { title: 'Deterrence of Criminal Activity', body: 'Visible surveillance cameras act as a significant deterrent to potential intruders. Criminals are less likely to target properties monitored by high-quality cameras, reducing risk of theft and vandalism.' },
      { title: 'Remote Access and Control', body: 'Smart security cameras allow property owners to monitor premises from any location using mobile devices — live footage, alerts, and camera control from anywhere.' },
      { title: 'High-Definition Video Recording', body: 'Modern surveillance systems offer clear, high-resolution images essential for identifying individuals, vehicles, and incidents. HD recordings are critical for investigations, insurance claims, and law enforcement.' },
      { title: 'Enhanced Employee and Property Monitoring', body: 'Surveillance systems support businesses in monitoring employee activity and ensuring workplace safety. Video evidence helps resolve disputes and safeguard sensitive areas.' },
      { title: 'Integration with Other Security Devices', body: 'Smart cameras can integrate with alarms, access control, and lighting solutions, providing a cohesive security ecosystem with automated responses and enhanced threat detection.' },
      { title: 'Peace of Mind and Safety Assurance', body: 'Knowing that a property is continuously monitored provides psychological comfort. Reliable video surveillance reduces anxiety about potential risks and ensures faster responses to incidents.' },
    ],
    closing_title: 'Professional Security Monitoring Solutions You Can Rely On',
    closing: 'Securing your home or business in South Florida requires more than just installing cameras — it requires a system that\'s designed properly and supported over time. At Octagon Security, we install high-quality video surveillance systems that provide clear footage, reliable performance, and easy remote access from anywhere.',
    faqs: [
      { q: 'What types of smart security cameras do you install in South Florida?', a: 'We install a range of smart security cameras including indoor, outdoor, wireless, and PTZ models. Each system is customized to meet specific monitoring needs, providing clear video, motion detection, and mobile access.' },
      { q: 'Can smart security cameras be monitored remotely?', a: 'Yes, all our smart cameras support remote monitoring via smartphones, tablets, or computers, allowing users to view live footage, receive alerts, and control camera settings from any location.' },
      { q: 'Are the surveillance systems weatherproof for outdoor use?', a: 'Absolutely. Outdoor security cameras are designed to withstand extreme weather conditions, including rain, heat, and humidity, providing reliable performance and consistent monitoring year-round.' },
      { q: 'How does video storage work for these systems?', a: 'Video footage can be stored locally on digital recorders or securely in cloud-based storage, ensuring easy retrieval of past recordings for investigation, compliance, or evidence purposes.' },
      { q: 'Can your systems be expanded in the future?', a: 'Absolutely. All smart security systems are scalable, allowing additional cameras or sensors to be added as needed without replacing the existing system.' },
    ],
  },

  'warehouse': {
    slug: 'warehouse',
    title: 'Warehouse Security Systems in Miami-Dade',
    location: 'Miami-Dade',
    hero_subtitle: 'Integrated Security Solutions for Warehouses and Distribution Centers',
    intro: 'Warehouses face unique security challenges including inventory protection, employee access management, loading dock activity, after-hours monitoring, and perimeter security. Octagon Security designs integrated warehouse security systems that combine video surveillance, access control, burglar alarms, and structured cabling to help protect people, property, and operations.',
    intro2: 'Whether you\'re securing a warehouse, distribution center, logistics facility, or industrial property, we provide scalable solutions designed for long-term reliability and operational visibility. Our systems help business owners monitor activity, control access, and respond quickly to security events from anywhere.',
    icon: 'building-2',
    image: '../../assets/svc-warehouse.png',
    features: [
      { title: 'Security Camera Systems', bullets: ['Monitor inventory, loading docks, and entrances', 'Parking area and perimeter coverage', 'Commercial-grade video surveillance', '24/7 visibility across all operations'], note: '' },
      { title: 'Access Control Systems', bullets: ['Key cards, mobile credentials, and key fobs', 'Managed entry points for employees and visitors', 'Improve security and accountability', 'Track and log all access activity'], note: '' },
      { title: 'Burglar Alarm Protection', bullets: ['Intrusion detection systems and monitored alarms', 'Motion sensors and perimeter security', 'Protect inventory, equipment, and facilities', 'Fast response from central monitoring'], note: '' },
      { title: 'Loading Dock Security', bullets: ['Monitor shipping and receiving activity', 'Track deliveries with strategically placed cameras', 'Controlled access points for dock areas', 'Improve operational visibility'], note: '' },
      { title: 'Structured Cabling & Network Infrastructure', bullets: ['Reliable CAT6 and fiber optic cabling', 'Supports cameras, access control, and wireless', 'Clean, organized installation', 'Built for long-term performance'], note: '' },
      { title: 'Remote Monitoring & Mobile Access', bullets: ['View cameras and manage users from anywhere', 'Receive alerts for activity and security events', 'Monitor via secure mobile applications', 'Remote management tools for complete control'], note: '' },
    ],
    benefits: [
      { title: 'Enhanced Property Protection', body: 'Detects unauthorized entry instantly, helping prevent theft, damage, and unauthorized access. High-quality equipment and precise installation ensure entry points are monitored and risks are minimized.' },
      { title: 'Remote Access & Alerts', body: 'Stay connected to your system with real-time notifications and control from your phone or device. Early detection of suspicious activity provides time to take action.' },
      { title: '24/7 Monitoring & Response', body: 'Modern security systems allow constant monitoring through mobile apps, computer dashboards, or control panels. Professional monitoring ensures alarms are handled quickly.' },
      { title: 'Visible Deterrence', body: 'Visible cameras, alarms, and access controls act as strong deterrents. Professionally installed systems reduce the likelihood of break-ins and unauthorized entry at warehouses.' },
      { title: 'System Integration', body: 'Works seamlessly with cameras, access control, and other systems for complete protection. Integration enables control of multiple systems from one centralized platform.' },
      { title: 'Scalable & Reliable', body: 'Easily expand your system as needed with dependable performance over time. Scalable solutions protect investments and adapt to changing operational needs.' },
    ],
    closing_title: 'Why Warehouses Choose Octagon Security',
    closing: 'Warehouses, distribution centers, and industrial facilities require security systems that are reliable, scalable, and designed for real-world operations. Octagon Security provides integrated solutions that combine video surveillance, access control, burglar alarms, and structured cabling to help protect inventory, employees, equipment, and daily operations.',
    faqs: [
      { q: 'What security cameras are best for warehouses?', a: 'Commercial-grade IP cameras with high-resolution video, remote viewing, and night vision capabilities are typically the best choice. Camera placement should cover entrances, loading docks, inventory areas, and exterior perimeters.' },
      { q: 'How many security cameras does a warehouse need?', a: 'The number of cameras depends on the facility size, layout, entrances, loading docks, and inventory areas. Most warehouse systems are custom designed based on the property\'s specific needs.' },
      { q: 'Can warehouse security cameras be viewed remotely?', a: 'Yes. Modern warehouse security systems allow authorized users to view live and recorded video from smartphones, tablets, and computers from virtually anywhere.' },
      { q: 'What access control system works best for a warehouse?', a: 'Most warehouses benefit from key card, key fob, or mobile credential systems that allow management to control access, track entry activity, and quickly add or remove users.' },
      { q: 'How can I secure loading docks and inventory areas?', a: 'A combination of security cameras, access control, intrusion detection, and proper lighting provides the most effective protection for loading docks, shipping areas, and valuable inventory.' },
    ],
  },

  'burglar-alarm': {
    slug: 'burglar-alarm',
    title: 'Advanced Burglar Alarm Installation & Intrusion Detection in South Florida',
    location: 'South Florida',
    hero_subtitle: 'Burglar Alarm Installation & Monitoring in South Florida',
    intro: 'At Octagon Security, we provide professional burglar alarm installation and 24/7 monitoring for businesses and homes across South Florida. Our systems are designed to detect threats immediately, reduce false alarms, and provide reliable protection backed by fast response and ongoing support. Whether you need a new system or an upgrade, we deliver solutions that are built to perform and easy to manage.',
    intro2: '',
    icon: 'bell-ring',
    image: '../../assets/svc-burglar-alarm.png',
    features: [
      { title: 'Complete Alarm Systems with 24/7 Monitoring', bullets: ['Burglar alarm system installation', 'Door, window, and motion detection sensors', 'Glass break and perimeter protection', '24/7 professional monitoring', 'Mobile alerts and remote control'], note: 'Our systems are designed to detect intrusion quickly and ensure immediate response when it matters.' },
      { title: 'Designed for Homes & Commercial Properties', bullets: ['Residential homes and multi-family properties', 'Warehouses and industrial facilities', 'Offices and commercial buildings', 'Retail and mixed-use properties'], note: 'Each system is tailored to your property layout, eliminating vulnerabilities and ensuring proper coverage.' },
      { title: 'Fast Response & Reliable Installation', bullets: ['Fast response to new inquiries', 'Quick turnaround on quotes', 'Efficient, clean installations'], note: 'With over 65 years of combined experience, we install systems correctly the first time.' },
      { title: 'Smart Alarm Integration', bullets: ['Mobile app control', 'Real-time notifications', 'Camera system integration', 'Access control systems'], note: 'This allows you to monitor and control your system from anywhere.' },
      { title: 'Ongoing Service & System Support', bullets: ['System maintenance and inspections', 'Troubleshooting and repairs', 'Monitoring services', 'System upgrades and expansions'], note: 'Most of our clients stay with us long-term because we stay responsive.' },
      { title: 'Common Reasons Clients Call Us', bullets: ['Need a new alarm system installed', 'Existing system not working properly', 'Frequent false alarms', 'Switching monitoring providers', 'Expanding or upgrading current system'], note: '' },
    ],
    benefits: [
      { title: 'Immediate Intrusion Detection', body: 'Detects unauthorized entry instantly using properly placed sensors and system design. This helps prevent theft, damage, and unauthorized access before it escalates.' },
      { title: '24/7 Monitoring & Response', body: 'Professional monitoring ensures alarms are handled immediately when triggered. Fast response helps minimize potential loss and keeps your property protected at all times.' },
      { title: 'Remote Access & Control', body: 'Monitor and control your system from anywhere with real-time alerts and mobile access. Stay informed of activity on your property whether you\'re on-site or away.' },
      { title: 'Visible Deterrence', body: 'Alarm systems and signage make your property a less attractive target for intruders. Most break-ins are avoided when proper security is clearly in place.' },
      { title: 'System Integration', body: 'Your alarm system can integrate with cameras, access control, and other systems. This creates a complete, easy-to-manage security solution from one platform.' },
      { title: 'Ongoing Service & Support', body: 'We stay involved after installation with maintenance, troubleshooting, and system upgrades. Our clients rely on us for continued support, not just the initial install.' },
    ],
    closing_title: 'Reliable Security Solutions for Your Peace of Mind',
    closing: 'A professionally installed alarm system provides more than basic protection — it delivers immediate intrusion detection, reliable 24/7 monitoring, and real-time alerts you can access from anywhere. With proper design and installation, systems operate more efficiently, reducing false alarms and improving overall reliability. As your needs grow, alarm systems can be expanded and integrated with cameras and access control, creating a complete, easy-to-manage security solution.',
    faqs: [
      { q: 'How long does it take to install a burglar alarm system?', a: 'Installation typically ranges from a few hours to a full day, depending on property size, complexity, and integration requirements. Our team ensures professional setup with minimal disruption to daily activities.' },
      { q: 'Can these systems integrate with smart home devices?', a: 'Yes, our systems are compatible with most smart home devices, including mobile apps, cameras, and automated notifications. This allows homeowners and business operators in Miami, Florida to control and monitor security from anywhere conveniently.' },
      { q: 'Are commercial properties supported?', a: 'Absolutely. We provide commercial intrusion detection solutions tailored for offices, retail spaces, warehouses, and multi-tenant buildings, ensuring professional security and compliance with safety standards.' },
      { q: 'What types of sensors are used in installations?', a: 'We use a combination of motion detectors, door/window sensors, glass break sensors, and video-based monitoring to ensure comprehensive coverage. Sensor placement is customized for each property to maximize protection and effectiveness.' },
      { q: 'Is ongoing maintenance necessary?', a: 'Yes, ongoing maintenance ensures that all components are functional, software is up-to-date, and false alarms are minimized. Regular service checks maintain optimal system performance, offering consistent security for properties.' },
      { q: 'How quickly can I receive an alarm response?', a: 'Professional monitoring ensures real-time alerts with emergency dispatch typically within minutes. Our systems are designed to prioritize immediate notification to authorities, safeguarding property efficiently.' },
      { q: 'Can I expand my system later if needed?', a: 'Absolutely. Our alarm systems are fully scalable, allowing clients to add sensors, cameras, or integrated devices over time without compromising performance, ensuring long-term flexibility.' },
      { q: 'Why should I choose Octagon Security?', a: 'With over 65 years of combined experience, Octagon Security provides tailored solutions throughout South Florida. Our expertise, reliability, and advanced technology ensure professional security for homes and businesses across the region.' },
    ],
  },

  'access-control': {
    slug: 'access-control',
    title: 'Access Control Systems & Keyless Entry Solutions in Miami, Florida',
    location: 'Miami, Florida',
    hero_subtitle: 'Optimizing Efficiency with Secure Property Management Solutions',
    intro: 'At Octagon Security, we provide professional access control and keyless entry systems for businesses and residential properties across South Florida. Our systems are designed to give you full control over who can access your property, when they can enter, and how access is managed.',
    intro2: 'Traditional keys create unnecessary risk and limited control. Our systems replace outdated locks with secure digital access using keycards, mobile credentials, biometric options, and programmable entry codes. Beyond installation, we provide ongoing support, system integration, and scalable solutions that grow with your needs.',
    icon: 'key-round',
    image: '../../assets/svc-keypad.png',
    features: [
      { title: 'Controlled Access to Entry Points', bullets: ['Manage entry permissions for employees and visitors', 'Eliminate key-related risks and lost credentials', 'Monitor and restrict access by time or zone', 'Ideal for offices, warehouses, multi-tenant properties, and residential applications'], note: '' },
      { title: 'Keyless Entry & Credential Management', bullets: ['Keycards and key fobs', 'Mobile credentials via smartphone', 'Programmable access codes', 'Biometric options including fingerprint and facial scan'], note: '' },
      { title: 'Activity Tracking & Audit Logs', bullets: ['Detailed logs of who accessed each entry point', 'Timestamps for all entry and exit events', 'Visibility into patterns and anomalies', 'Documentation for accountability and compliance'], note: '' },
      { title: 'Remote Access & System Control', bullets: ['Manage your system from anywhere', 'Add or remove users remotely', 'Unlock doors from your phone', 'Real-time notifications for access events'], note: '' },
      { title: 'Integration with Security Systems', bullets: ['Combines with cameras for complete visual coverage', 'Integrates with alarms and monitoring platforms', 'Centralized control of all security systems', 'Scalable with your existing infrastructure'], note: '' },
      { title: 'Scalable & Reliable Systems', bullets: ['Easily expand to additional doors and users', 'Built for single-entry and multi-door installations', 'Dependable long-term performance', 'Ongoing support and system updates'], note: '' },
    ],
    benefits: [
      { title: 'Controlled Access to Entry Points', body: 'Manage entry permissions and eliminate key-related risks. Access control systems give you full visibility into who enters your property and when.' },
      { title: 'Keyless Entry & Credential Management', body: 'Replace traditional locks with secure digital credentials — keycards, fobs, mobile credentials, and access codes that can be changed or revoked instantly.' },
      { title: 'Activity Tracking & Audit Logs', body: 'Detailed system logs provide visibility and accountability across all access points, helping you identify issues and meet compliance requirements.' },
      { title: 'Remote Access & System Control', body: 'Manage systems remotely, add users, and unlock doors from anywhere using a secure mobile application or web interface.' },
      { title: 'Integration with Security Systems', body: 'Access control solutions integrate seamlessly with CCTV, alarms, and management software for a complete security ecosystem.' },
      { title: 'Scalable & Reliable Systems', body: 'Systems expand with additional doors and users as your needs grow. Built for performance, scalability, and long-term use.' },
    ],
    closing_title: 'Access Control Systems Built for South Florida Properties',
    closing: 'Access control systems are a key part of modern property security, giving you better control over who can enter and how access is managed. From single-entry setups to larger multi-door systems, our solutions are built for performance, scalability, and long-term use.',
    faqs: [
      { q: 'What types of keyless entry solutions do you offer?', a: 'We provide keycard systems, biometric access, and mobile credential solutions designed for seamless operation.' },
      { q: 'How do biometric access systems work?', a: 'Biometric systems use unique physical characteristics such as fingerprints, facial scans, or retina patterns to grant access.' },
      { q: 'Can access control systems be integrated with existing security networks?', a: 'Yes, our access control solutions can seamlessly integrate with existing CCTV, alarms, and management software.' },
      { q: 'Are these systems suitable for residential properties?', a: 'Absolutely. Access control and keyless entry systems are ideal for single-family homes, condominiums, and gated communities.' },
      { q: 'How secure are mobile credential access systems?', a: 'Mobile credentials use encrypted communication between the device and access points, ensuring high security.' },
      { q: 'What support is available after installation?', a: 'Our team provides comprehensive ongoing maintenance, software updates, and troubleshooting services.' },
      { q: 'Can multiple locations be managed from a single system?', a: 'Yes, our advanced systems allow centralized management of multiple sites from a single interface.' },
    ],
  },

  'fire-alarm': {
    slug: 'fire-alarm',
    title: 'Fire Alarm Systems Installations, Testing & Inspections — Miami, Florida',
    location: 'Miami, Florida',
    hero_subtitle: 'Fire Alarm Installations & Inspection Services South Florida',
    intro: 'Octagon Security provides complete fire alarm solutions including installation, inspections, monitoring, and ongoing service for properties across Miami-Dade, Broward, and Palm Beach.',
    intro2: 'Our team handles fire alarm system installation, annual inspections and testing, 24/7 fire alarm monitoring, troubleshooting and repairs, and system upgrades and expansions — for commercial buildings and offices, warehouses and industrial facilities, multi-family and residential properties, and new construction.',
    icon: 'flame',
    image: '../../assets/svc-smoke.png',
    features: [
      { title: 'Fire Alarm System Installation', bullets: ['Commercial buildings and offices', 'Warehouses and industrial facilities', 'Multi-family and residential properties', 'New construction and system upgrades'], note: 'Every installation is designed to meet local, state, and national fire safety codes.' },
      { title: 'Inspection & Testing Services', bullets: ['Annual and scheduled fire alarm inspections', 'System testing and verification', 'Troubleshooting and repairs', 'Documentation for compliance requirements'], note: '' },
      { title: '24/7 Fire Alarm Monitoring', bullets: ['Constant monitoring for fire and smoke hazards', 'Immediate notification to emergency contacts or fire departments', 'Rapid response to alarms', 'Integration with central monitoring stations'], note: '' },
      { title: 'Fast Response & Professional Installation', bullets: ['Fast response to new inquiries', 'Quick turnaround on quotes and scheduling', 'Clean, organized installations', 'Over 65 years of combined experience'], note: 'Our clients rely on us to respond when it matters — and follow through.' },
      { title: 'Integrated Systems', bullets: ['Cameras, alarm systems, access control, and fire systems', 'Centralized monitoring', 'Remote access', 'Real-time alerts'], note: 'Your fire system can be integrated with cameras, alarms, and access control into one platform.' },
      { title: 'Ongoing Support', bullets: ['System maintenance and inspections', 'Troubleshooting and repairs', 'Monitoring services', 'System upgrades as your needs grow'], note: '' },
    ],
    benefits: [
      { title: 'Early Fire Detection', body: 'Early detection significantly reduces the risk of injury and property loss. Smoke and heat detectors identify hazards before flames spread, allowing occupants to evacuate safely.' },
      { title: 'Compliance with Safety Regulations', body: 'Professional installation ensures systems meet local, state, and national fire safety codes, reducing legal liabilities and ensuring insurance coverage eligibility.' },
      { title: 'Enhanced Property Protection', body: 'Systems safeguard homes and businesses against fire damage through integrated coverage across multiple zones.' },
      { title: '24/7 Monitoring & Alerts', body: 'Constant monitoring ensures that potential fire hazards are immediately reported to emergency contacts or fire departments.' },
      { title: 'Reduced Insurance Costs', body: 'Properties with professionally installed fire alarm systems may qualify for lower insurance premiums.' },
      { title: 'Peace of Mind for Occupants', body: 'Professionally installed fire alarm systems offer reassurance for homeowners, tenants, and employees.' },
    ],
    closing_title: 'Why Choose Octagon Security for Fire Alarm Installation',
    closing: 'Choosing professional fire alarm installation ensures your property is properly protected, your system meets code requirements, and everything works together as intended. With 65+ years of combined experience and a focus on clean installations and long-term support, Octagon Security is a reliable partner for fire protection across South Florida.',
    faqs: [
      { q: 'Why is professional fire alarm installation important?', a: 'Professional installation ensures proper placement, code compliance, and system reliability.' },
      { q: 'How often should fire alarm systems be tested?', a: 'Fire alarm systems should be tested at least once every six months.' },
      { q: 'Can fire alarm systems integrate with smart home devices?', a: 'Yes, modern fire alarm systems can integrate with smart home devices.' },
      { q: 'What areas does Octagon Security serve?', a: 'Octagon Security serves all of South Florida, including Miami-Dade, Broward, and Palm Beach.' },
      { q: 'How long does fire alarm installation take?', a: 'Residential installations may take a few hours, while larger commercial projects may require a full day or more.' },
      { q: 'What maintenance services do you provide?', a: 'Services include inspection, testing, component replacement, and system calibration.' },
      { q: 'What types of smoke detectors do you install?', a: 'We install ionization, photoelectric, and dual-sensor smoke detectors depending on the property and application.' },
      { q: 'Do commercial properties benefit from 24/7 monitoring?', a: 'Yes. Commercial properties benefit from 24/7 monitoring, ensuring rapid notification to fire departments.' },
    ],
  },

  'structured-cabling': {
    slug: 'structured-cabling',
    title: 'Structured Cabling Installation in South Florida',
    location: 'South Florida',
    hero_subtitle: 'Reliable network cabling solutions for offices, warehouses, retail locations, healthcare facilities, and commercial properties throughout Miami-Dade and Broward County.',
    intro: 'At Octagon Security, we provide professional structured cabling solutions for offices, warehouses, retail locations, healthcare facilities, and commercial properties throughout South Florida. Our team designs and installs reliable network infrastructure including CAT6 cabling, fiber optic cabling, data drops, patch panels, network racks, and wireless access point cabling. Whether you\'re building a new facility or upgrading an existing network, we deliver organized, scalable cabling systems designed for long-term performance.',
    intro2: 'Reliable network infrastructure is the foundation of modern business operations. Octagon Security provides structured cabling solutions that support computers, phones, wireless access points, security cameras, access control systems, and other connected technologies. Our installations are organized, scalable, and designed to support future growth.',
    icon: 'cable',
    image: '../../assets/team-ladders.png',
    features: [
      { title: 'CAT6 & CAT6A Cabling', bullets: ['Offices, warehouses, retail stores, healthcare facilities, and commercial properties'], note: 'Professional network cabling installations designed for reliable performance and future expansion.' },
      { title: 'Fiber Optic Cabling', bullets: ['Building-to-building connections', 'Equipment rooms', 'Long-distance network infrastructure'], note: 'High-speed fiber optic backbone installations for demanding network infrastructure requirements.' },
      { title: 'Data Drops & Workstation Cabling', bullets: ['Data outlets and workstation connections', 'Network cabling for computers, phones, and printers', 'Connected devices throughout your facility'], note: 'Installation of data outlets, workstation connections, and network cabling.' },
      { title: 'Network Racks & Patch Panels', bullets: ['Rack installation and cable management', 'Patch panels and equipment mounting', 'Structured wiring systems'], note: 'Organized network infrastructure for easy maintenance and long-term reliability.' },
      { title: 'Wireless Access Point Cabling', bullets: ['Offices, warehouses, and commercial facilities', 'Reliable Wi-Fi coverage throughout your space'], note: 'Cabling and mounting solutions for wireless access points.' },
      { title: 'Warehouse & Commercial Network Infrastructure', bullets: ['Warehouses and distribution centers', 'Manufacturing facilities', 'Growing commercial operations'], note: 'Scalable network cabling solutions designed for real-world operations and future growth.' },
    ],
    benefits: [
      { title: 'Improved Network Performance', body: 'Modern structured cabling improves network reliability, supports higher data speeds, reduces connectivity issues, and provides a stronger foundation for business operations and wireless networks.' },
      { title: 'Scalable Infrastructure', body: 'Installations are organized and designed to support future growth — additional drops, wireless access points, and connected devices can be added as your needs evolve.' },
      { title: 'Supports Security Systems', body: 'Structured cabling provides the network infrastructure required for IP security cameras, access control readers, and other security technologies throughout your facility.' },
      { title: 'PoE for Connected Devices', body: 'Power over Ethernet allows network cables to deliver both data and electrical power to cameras, wireless access points, and access control equipment.' },
      { title: 'Organized & Maintainable', body: 'Network racks, patch panels, and clean cable management simplify maintenance, troubleshooting, and future changes to your infrastructure.' },
      { title: 'Built for Commercial & Warehouse Use', body: 'Scalable solutions for offices, warehouses, distribution centers, and manufacturing facilities — designed for real-world operations and long-term performance.' },
    ],
    closing_title: 'Structured Cabling Solutions for Modern Businesses',
    closing: 'Reliable network infrastructure is the foundation of today\'s connected business environment. Octagon Security provides professional structured cabling services that support computers, phones, wireless access points, security cameras, access control systems, and other network-connected technologies. Our installations are organized, scalable, and designed to support future growth. Whether you\'re outfitting a new office, expanding a warehouse, upgrading an existing network, or building a new facility from the ground up, we deliver structured cabling solutions that provide long-term reliability and performance.',
    faqs: [
      { q: 'What is structured cabling?', a: 'Structured cabling is an organized network infrastructure system that supports data, voice, wireless access points, security systems, and other communication technologies within a building or facility.' },
      { q: 'What is the difference between CAT5e and CAT6 cabling?', a: 'CAT6 cabling generally supports higher data speeds and improved performance compared to CAT5e. CAT6 is commonly recommended for new commercial installations to support current and future network demands.' },
      { q: 'How many data drops does my business need?', a: 'The number of data drops depends on workstations, wireless access points, security devices, printers, phones, and future expansion plans. A site survey can help determine the proper quantity and placement.' },
      { q: 'Can structured cabling support security cameras and access control?', a: 'Yes. Structured cabling provides the network infrastructure required for IP security cameras, access control readers, controllers, and other security technologies.' },
      { q: 'What is PoE (Power over Ethernet)?', a: 'Power over Ethernet allows network cables to deliver both data and electrical power to compatible devices such as cameras, wireless access points, and access control equipment.' },
      { q: 'When should fiber optic cabling be used?', a: 'Fiber is commonly used between buildings, equipment rooms, telecommunications closets, and locations where long cable distances or high bandwidth requirements exist.' },
      { q: 'Can structured cabling be installed in existing buildings?', a: 'Yes. Structured cabling can often be installed in occupied buildings, offices, warehouses, and commercial facilities with minimal disruption to operations.' },
      { q: 'What areas does Octagon Security serve for structured cabling?', a: 'Octagon Security provides structured cabling, network wiring, fiber optic installation, and communications infrastructure services throughout Miami-Dade County, Broward County, and surrounding South Florida communities.' },
    ],
  },
};
